[versions]
# Android & Kotlin
kotlin = "2.1.10"
android-gradle-plugin = "8.7.3"
kotlin-symbol-processor = "2.1.10-1.0.31"
kotlinx-coroutines = "1.10.2"

# AndroidX Core
androidx-core = "1.15.0"
androidx-core-splashscreen = "1.2.0"
androidx-appcompat = "1.7.0"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.0"
androidx-startup = "1.2.0"
androidx-work = "2.10.0"
androidx-paging = "3.3.6"
androidx-profileinstaller = "1.4.1"

# Jetpack Compose
androidx-compose-bom = "2025.02.00"
androidx-compose-material3 = "1.3.1"
androidx-compose-material3-adaptive = "1.1.0"
androidx-constraintlayout-compose = "1.1.1"
androidx-navigation = "2.8.9"
androidx-compose-material = "1.7.8"

# Hilt & Dagger
google-dagger = "2.55"
androidx-hilt = "1.2.0"

# TV & Media
androidx-tv = "1.0.0-alpha10"
androidx-tv-foundation = "1.0.0-alpha10"
androidx-media3 = "1.6.0"
glance = "1.1.1"

# Storage
androidx-room = "2.7.1"
datastore = "1.1.3"

# UI & Graphics
androidx-graphics-shapes = "1.0.1"
haze = "1.3.0"
io-coil = "2.7.0"
lottie-compose = "6.6.4"
minabox = "1.9.0"
google-accompanist = "0.36.0"

# Networking
dropbox-core = "7.0.0"
squareup-retrofit2 = "2.11.0"
okhttp = "4.12.0"
gson = "2.11.0"
ktor-server = "2.3.13"
mm2d-mmupnp = "3.1.6"
jsoup = "1.18.3"

# Serialization
kotlinx-serialization-json = "1.8.0"
kotlinx-serialization-converter-retrofit = "1.0.0"
kotlinx-datetime = "0.6.1"

# Code Generation
kotlinpoet = "1.17.0"
auto-annotations = "1.1.1"
auto-ksp = "1.1.0"
squareup-wire = "4.9.9"
wireRuntime = "4.9.9"

# M3U Plugin
m3u-plugin = "1.9"

# Debugging & Monitoring
chucker = "4.1.0"
squareup-leakcanary = "2.14"
acra = "5.12.0"
timber = "5.0.1"

# Logging
logback = "1.5.6"
slf4j-api = "2.0.13"

# Media Libraries
nextLib = "0.8.5"

# Testing
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
androidx-test-uiautomator = "2.3.0"
androidx-benchmark = "1.3.3"

# Material Design
com-google-android-material = "1.12.0"

# Utilities
disklrucache = "2.0.2"
ffmpeg-kit = "6.0"
vlc-android = "3.6.0-eap11"
ijkplayer = "0.8.8"
newpipe-extractor = "v0.24.5"
mpv-lib = "0.1.10"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }

# Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle" }

# Compose BOM & Libraries
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

# Material3 Adaptive
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidx-compose-material3-adaptive" }

# Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

# ConstraintLayout
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }

# Hilt & Dagger
google-dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-dagger" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-dagger" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt" }

# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }

# TV
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "androidx-tv" }
androidx-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "androidx-tv-foundation" }

# Media3
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidx-media3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "androidx-media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidx-media3" }
androidx-media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "androidx-media3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "androidx-media3" }
androidx-media3-exoplayer-smoothstreaming = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "androidx-media3" }
androidx-media3-exoplayer-workmanager = { group = "androidx.media3", name = "media3-exoplayer-workmanager", version.ref = "androidx-media3" }
androidx-media3-container = { group = "androidx.media3", name = "media3-container", version.ref = "androidx-media3" }
androidx-media3-datasource-rtmp = { group = "androidx.media3", name = "media3-datasource-rtmp", version.ref = "androidx-media3" }
androidx-media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "androidx-media3" }
androidx-media3-extractor = { group = "androidx.media3", name = "media3-extractor", version.ref = "androidx-media3" }
androidx-media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "androidx-media3" }
androidx-media3-muxer = { group = "androidx.media3", name = "media3-muxer", version.ref = "androidx-media3" }

# Glance (Widgets)
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }

# DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Paging
androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }

# Graphics
androidx-graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes-android", version.ref = "androidx-graphics-shapes" }

# Material Design
google-material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material" }
jakewharton-disklrucache = { group = "com.jakewharton", name = "disklrucache", version.ref = "disklrucache" }

# Image Loading
io-coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "io-coil" }
io-coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "io-coil" }

# UI Effects
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
airbnb-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }
minabox = { group = "io.github.oleksandrbalan", name = "minabox", version.ref = "minabox" }

# Permissions
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "google-accompanist" }

# Networking
dropbox-core-sdk = { group = "com.dropbox.core", name = "dropbox-core-sdk", version.ref = "dropbox-core" }
squareup-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareup-retrofit2" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "squareup-retrofit2" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
net-mm2d-mmupnp = { group = "net.mm2d.mmupnp", name = "mmupnp", version.ref = "mm2d-mmupnp" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

# Ktor Server
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor-server" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets-jvm", version.ref = "ktor-server" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor-server" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor-server" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-server" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-converter-retrofit = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter-retrofit" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Code Generation
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-annotations" }
auto-service-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "auto-ksp" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kotlin-symbol-processor" }

# Wire (Protocol Buffers)
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wireRuntime" }

# M3U Plugin
m3u-plugin-api = { module = "com.github.oxyroid.m3u-extension:api", version.ref = "m3u-plugin" }
m3u-plugin-annotation = { module = "com.github.oxyroid.m3u-extension:annotation", version.ref = "m3u-plugin" }
m3u-plugin-processor = { module = "com.github.oxyroid.m3u-extension:processor", version.ref = "m3u-plugin" }
newpipe-extractor = { group = "com.github.TeamNewPipe", name = "NewPipeExtractor", version.ref = "newpipe-extractor" }

# Media Libraries
nextlib-media3ext = { module = "com.github.sintrs.nextlib:nextlib-media3ext", version.ref = "nextLib" }
nextlib-mediainfo = { module = "com.github.sintrs.nextlib:nextlib-mediainfo", version.ref = "nextLib" }
ffmpeg-kit-full = { module = "com.github.tanersener:ffmpeg-kit-full", version.ref = "ffmpeg-kit" }

# LibVLC
vlc-android = { module = "org.videolan.android:libvlc-all", version.ref = "vlc-android" }

# IJKPlayer
ijkplayer-java = { module = "tv.danmaku.ijk.media:ijkplayer-java", version.ref = "ijkplayer" }
ijkplayer-armv7a = { module = "tv.danmaku.ijk.media:ijkplayer-armv7a", version.ref = "ijkplayer" }
ijkplayer-arm64 = { module = "tv.danmaku.ijk.media:ijkplayer-arm64", version.ref = "ijkplayer" }
ijkplayer-x86 = { module = "tv.danmaku.ijk.media:ijkplayer-x86", version.ref = "ijkplayer" }
ijkplayer-x86-64 = { module = "tv.danmaku.ijk.media:ijkplayer-x86_64", version.ref = "ijkplayer" }

# MPV
mpv-lib = { module = "io.github.abdallahmehiz:mpv-android-lib", version.ref = "mpv-lib" }

# Debugging
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
squareup-leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "squareup-leakcanary" }
acra-core = { group = "ch.acra", name = "acra-core", version.ref = "acra" }
acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acra" }
acra-notification = { group = "ch.acra", name = "acra-notification", version.ref = "acra" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Logging
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
logback-android = { group = "com.github.tony19", name = "logback-android", version = "3.0.0" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-api" }

# Testing
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }

androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profileinstaller" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
com-android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
com-squareup-wire = { id = "com.squareup.wire", version.ref = "squareup-wire" }